// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9yLYokqc9FRaKyv7UZXe29R639Bl4mu8',
    appId: '1:2361398172:web:22aeef2203c37dd9402e59',
    messagingSenderId: '2361398172',
    projectId: 'staysync-aa3ce',
    authDomain: 'staysync-aa3ce.firebaseapp.com',
    storageBucket: 'staysync-aa3ce.appspot.com',
    measurementId: 'G-EPNKTCTJJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL_1pYB_LZfJ1EZlu2tBb-1YyI8H_bZ-4',
    appId: '1:2361398172:android:c804e04ae551fe72402e59',
    messagingSenderId: '2361398172',
    projectId: 'staysync-aa3ce',
    storageBucket: 'staysync-aa3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD70U1i39mZ0U76vlCDvNp2NmCtnwOKXeU',
    appId: '1:2361398172:ios:95e7269774ace1c8402e59',
    messagingSenderId: '2361398172',
    projectId: 'staysync-aa3ce',
    storageBucket: 'staysync-aa3ce.appspot.com',
    iosBundleId: 'com.example.uuHostelManagement',
  );
}
